// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOCr7ohR57Kgdq4BcK3cF_pjcpuUySYo',
    appId: '1:9100724744:android:1261616bb832f960159fbd',
    messagingSenderId: '9100724744',
    projectId: 'smartwatch-96185',
    databaseURL: 'https://smartwatch-96185-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartwatch-96185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPIbQZjinBiNMwMLBLPl8KPU71gfIik8',
    appId: '1:9100724744:ios:6c437a36197a59bf159fbd',
    messagingSenderId: '9100724744',
    projectId: 'smartwatch-96185',
    databaseURL: 'https://smartwatch-96185-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smartwatch-96185.appspot.com',
    iosClientId: '9100724744-05th2289g581p9ashj9ohmc8r8b4alh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWatch',
  );
}
